


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."fn_insert_sensor_row_for_new_plant"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  insert into public.sensor_data (plant_id)
  values (NEW.id);

  update public."User_Plants"
  set sensor_data = NEW.id
  where id = NEW.id;   

  return new;
end;$$;


ALTER FUNCTION "public"."fn_insert_sensor_row_for_new_plant"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_chat_list"() RETURNS TABLE("other_user_id" "uuid", "last_message_content" "text", "last_message_time" timestamp with time zone, "unread_count" bigint)
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  RETURN QUERY
  SELECT
    sub.other_user_id,
    m.content AS last_message_content,
    m.created_at AS last_message_time,
    (
      SELECT COUNT(*)
      FROM messages unread_m
      WHERE unread_m.sender_id = sub.other_user_id
        AND unread_m.receiver_id = auth.uid()
        AND unread_m.is_read = false
    ) as unread_count
  FROM (
    SELECT
      DISTINCT ON (
        CASE
          WHEN sender_id = auth.uid() THEN receiver_id
          ELSE sender_id
        END
      )
      CASE
        WHEN sender_id = auth.uid() THEN receiver_id
        ELSE sender_id
      END as other_user_id,
      id as last_message_id
    FROM messages
    WHERE sender_id = auth.uid() OR receiver_id = auth.uid()
    ORDER BY other_user_id, created_at DESC
  ) AS sub
  JOIN messages m ON sub.last_message_id = m.id
  ORDER BY m.created_at DESC;
END;
$$;


ALTER FUNCTION "public"."get_chat_list"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
BEGIN
  -- auth.users의 정보를 public."Users" 테이블에 삽입합니다.
  INSERT INTO public."Users" (id, email, name)
  VALUES (
    NEW.id,
    NEW.email,
    NEW.raw_user_meta_data->>'full_name' -- 소셜 로그인 시 제공되는 이름
  );
  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."insert_sensor_data"("p_plant_id" "uuid", "p_temp" "jsonb", "p_humidity" "jsonb", "p_light" "jsonb") RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.sensor_data (plant_id, temp, humidity, light, created_at)
  values (
    p_plant_id,
    jsonb_build_array(p_temp),
    jsonb_build_array(p_humidity),
    jsonb_build_array(p_light),
    now()
  )
  on conflict (plant_id) do update
  set temp       = jsonb_build_array(p_temp)     || coalesce(public.sensor_data.temp, '[]'::jsonb),
      humidity   = jsonb_build_array(p_humidity) || coalesce(public.sensor_data.humidity, '[]'::jsonb),
      light      = jsonb_build_array(p_light)    || coalesce(public.sensor_data.light, '[]'::jsonb),
      created_at = now();

  return p_plant_id;
end;
$$;


ALTER FUNCTION "public"."insert_sensor_data"("p_plant_id" "uuid", "p_temp" "jsonb", "p_humidity" "jsonb", "p_light" "jsonb") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."AI_view" (
    "photos" bigint NOT NULL,
    "sensor_data" "jsonb" NOT NULL
);


ALTER TABLE "public"."AI_view" OWNER TO "postgres";


ALTER TABLE "public"."AI_view" ALTER COLUMN "photos" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."AI_view_photos_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Post" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "user_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "category" bigint,
    "price" numeric,
    "photos" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."Post" OWNER TO "postgres";


ALTER TABLE "public"."Post" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Post_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User_Plants" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text",
    "photos" "jsonb",
    "rank" json,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" bigint,
    "user_id" "uuid",
    "sensor_data" "uuid",
    "locate" "text"
);


ALTER TABLE "public"."User_Plants" OWNER TO "postgres";


COMMENT ON TABLE "public"."User_Plants" IS '유저의 식물들.';



CREATE TABLE IF NOT EXISTS "public"."Users" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "email" "text" NOT NULL,
    "password" "text",
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "posts(list)" bigint[],
    "message" "jsonb",
    "plants" "jsonb",
    "avatar_url" "text"
);


ALTER TABLE "public"."Users" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."category_list" (
    "id" bigint NOT NULL,
    "category" "text" NOT NULL
);


ALTER TABLE "public"."category_list" OWNER TO "postgres";


ALTER TABLE "public"."category_list" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_list_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "content" "text" NOT NULL,
    "sender_id" "uuid" NOT NULL,
    "receiver_id" "uuid" NOT NULL
);


ALTER TABLE "public"."messages" OWNER TO "postgres";


COMMENT ON TABLE "public"."messages" IS '1:1 채팅 메시지를 저장합니다.';



ALTER TABLE "public"."messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."plants_data" (
    "plant_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "name" "text" NOT NULL,
    "sensor_data_range" json,
    "data" "text",
    "logs" json,
    "price_list" numeric,
    "avg.price" numeric,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."plants_data" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."sensor_data" (
    "plant_id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "humidity" "jsonb",
    "temp" "jsonb",
    "light" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "plant_category" "uuid"
);


ALTER TABLE "public"."sensor_data" OWNER TO "postgres";


ALTER TABLE ONLY "public"."AI_view"
    ADD CONSTRAINT "AI_view_pkey" PRIMARY KEY ("photos");



ALTER TABLE ONLY "public"."Post"
    ADD CONSTRAINT "Post_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "User_Plants_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "User_Plants_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."Users"
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."category_list"
    ADD CONSTRAINT "category_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."plants_data"
    ADD CONSTRAINT "plants_master_pkey" PRIMARY KEY ("plant_id");



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_humudity_key" UNIQUE ("humidity");



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_light_key" UNIQUE ("light");



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_pkey" PRIMARY KEY ("plant_id");



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_temp_key" UNIQUE ("temp");



CREATE INDEX "messages_sender_receiver_idx" ON "public"."messages" USING "btree" ("sender_id", "receiver_id");



CREATE OR REPLACE TRIGGER "trg_user_plants_insert_sensor_row" AFTER INSERT ON "public"."User_Plants" FOR EACH ROW EXECUTE FUNCTION "public"."fn_insert_sensor_row_for_new_plant"();



ALTER TABLE ONLY "public"."Post"
    ADD CONSTRAINT "Post_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."category_list"("id");



ALTER TABLE ONLY "public"."Post"
    ADD CONSTRAINT "Post_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "User_Plants_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."category_list"("id");



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "User_Plants_sensor_data_fkey" FOREIGN KEY ("sensor_data") REFERENCES "public"."sensor_data"("plant_id");



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "User_Plants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_receiver_id_fkey" FOREIGN KEY ("receiver_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."messages"
    ADD CONSTRAINT "messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Post"
    ADD CONSTRAINT "post_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_plant_category_fkey" FOREIGN KEY ("plant_category") REFERENCES "public"."plants_data"("plant_id");



ALTER TABLE ONLY "public"."sensor_data"
    ADD CONSTRAINT "sensor_data_plant_id_fkey" FOREIGN KEY ("plant_id") REFERENCES "public"."User_Plants"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."User_Plants"
    ADD CONSTRAINT "user_plants_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."Users"("id") ON DELETE CASCADE;



ALTER TABLE "public"."AI_view" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Allow authenticated users to read profiles" ON "public"."Users" FOR SELECT USING (("auth"."role"() = 'authenticated'::"text"));



CREATE POLICY "Allow individual update access to own profile" ON "public"."Users" FOR DELETE USING (("auth"."uid"() = "id"));



CREATE POLICY "Allow public read access to profiles" ON "public"."Users" FOR SELECT USING (true);



CREATE POLICY "Allow users to insert their own profile" ON "public"."Users" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Allow users to update their own profile" ON "public"."Users" FOR UPDATE USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Enable read access for all users" ON "public"."sensor_data" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."Post" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."Users" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can insert their own messages." ON "public"."messages" FOR INSERT WITH CHECK (("auth"."uid"() = "sender_id"));



CREATE POLICY "Users can view their own messages." ON "public"."messages" FOR SELECT USING ((("auth"."uid"() = "sender_id") OR ("auth"."uid"() = "receiver_id")));



ALTER TABLE "public"."category_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."messages" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."plants_data" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sensor_data" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."fn_insert_sensor_row_for_new_plant"() TO "anon";
GRANT ALL ON FUNCTION "public"."fn_insert_sensor_row_for_new_plant"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."fn_insert_sensor_row_for_new_plant"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_chat_list"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_chat_list"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_chat_list"() TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."insert_sensor_data"("p_plant_id" "uuid", "p_temp" "jsonb", "p_humidity" "jsonb", "p_light" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "public"."insert_sensor_data"("p_plant_id" "uuid", "p_temp" "jsonb", "p_humidity" "jsonb", "p_light" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "public"."insert_sensor_data"("p_plant_id" "uuid", "p_temp" "jsonb", "p_humidity" "jsonb", "p_light" "jsonb") TO "service_role";


















GRANT ALL ON TABLE "public"."AI_view" TO "anon";
GRANT ALL ON TABLE "public"."AI_view" TO "authenticated";
GRANT ALL ON TABLE "public"."AI_view" TO "service_role";



GRANT ALL ON SEQUENCE "public"."AI_view_photos_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."AI_view_photos_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."AI_view_photos_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Post" TO "anon";
GRANT ALL ON TABLE "public"."Post" TO "authenticated";
GRANT ALL ON TABLE "public"."Post" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Post_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Post_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Post_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."User_Plants" TO "anon";
GRANT ALL ON TABLE "public"."User_Plants" TO "authenticated";
GRANT ALL ON TABLE "public"."User_Plants" TO "service_role";



GRANT ALL ON TABLE "public"."Users" TO "anon";
GRANT ALL ON TABLE "public"."Users" TO "authenticated";
GRANT ALL ON TABLE "public"."Users" TO "service_role";



GRANT ALL ON TABLE "public"."category_list" TO "anon";
GRANT ALL ON TABLE "public"."category_list" TO "authenticated";
GRANT ALL ON TABLE "public"."category_list" TO "service_role";



GRANT ALL ON SEQUENCE "public"."category_list_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_list_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_list_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."messages" TO "anon";
GRANT ALL ON TABLE "public"."messages" TO "authenticated";
GRANT ALL ON TABLE "public"."messages" TO "service_role";



GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."messages_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."plants_data" TO "anon";
GRANT ALL ON TABLE "public"."plants_data" TO "authenticated";
GRANT ALL ON TABLE "public"."plants_data" TO "service_role";



GRANT ALL ON TABLE "public"."sensor_data" TO "anon";
GRANT ALL ON TABLE "public"."sensor_data" TO "authenticated";
GRANT ALL ON TABLE "public"."sensor_data" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































